-- MySQL Script generated by MySQL Workbench
-- Sat Feb 18 17:57:59 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ece1779_a2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ece1779_a2` DEFAULT CHARACTER SET utf8;
USE `ece1779_a2`;

-- -----------------------------------------------------
-- Table `ece1779_a2`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ece1779_a2`.`images`;

CREATE TABLE IF NOT EXISTS `ece1779_a2`.`images` (
  `id`       INT          NOT NULL AUTO_INCREMENT,
  `key`      VARCHAR(255) NOT NULL UNIQUE,
  `path`     VARCHAR(255) NOT NULL UNIQUE DEFAULT '/',
  `size`     INT          NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)ENGINE = InnoDB;

-- INSERT INTO images VALUES (1, 'abcdefgh');
-- INSERT INTO images(`id`, `key`) VALUES (3, 'abcdefgh');
-- INSERT INTO images(`key`) VALUES ('abcd');

-- SELECT `key` from images ORDER BY `id` DESC LIMIT 2;
-- SELECT `key` from images  WHERE `id` > 2 ORDER BY `id` LIMIT 1;
-- SELECT `id` FROM images WHERE `key` IN ('im no 1', 'bba');
-- SELECT *  FROM images WHERE `key` IN ('im no 1', 'bba') ORDER BY `id` DESC;

-- DELETE FROM images WHERE `key` = 'abc';

-- UPDATE images SET `key` = %s WHERE `id` = %s

-- -----------------------------------------------------
-- Table `ece1779_a2`.`accesses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ece1779_a2`.`accesses`;

CREATE TABLE IF NOT EXISTS `ece1779_a2`.`accesses` (
  `tid`     INT          NOT NULL,
  `miss`    INT          NOT NULL,
  `hit`     INT          NOT NULL,
  `cap`     INT          NOT NULL,
  PRIMARY KEY (`tid`,`miss`,`hit`)
)ENGINE = InnoDB;

-- INSERT INTO accesses VALUES (1, 2, 3, 4 );
-- INSERT INTO accesses(`miss`, `hit`, `cap`) VALUES (2, 3, 3);

SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
